# Generated by Django 5.2 on 2025-04-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_announcementread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementread',
            name='announcement',
            field=models.ForeignKey(db_column='announcement_id', on_delete=django.db.models.deletion.CASCADE, to='attendance.announcement'),
        ),
        migrations.CreateModel(
            name='Attendance_LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance_employee_data')),
            ],
            options={
                'db_table': 'attendance_leave_request',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
