# Generated by Django 5.2 on 2025-04-12 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_announcementread_announcement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_leaverequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='attendance_leaverequest',
            old_name='date',
            new_name='from_date',
        ),
        migrations.AlterUniqueTogether(
            name='attendance_leaverequest',
            unique_together={('employee', 'from_date')},
        ),
        migrations.AddField(
            model_name='attendance_leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('other', 'Other')], default='sick', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance_leaverequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance_leaverequest',
            name='to_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.RemoveField(
            model_name='attendance_leaverequest',
            name='reason',
        ),
    ]
