# Generated by Django 5.2 on 2025-04-17 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_attendance_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_leaverequest',
            name='from_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
