# Generated by Django 3.2.7 on 2025-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20250515_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_leaverequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='attendance_leaverequest',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance_leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
