# Generated by Django 3.2.7 on 2025-05-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_holiday_and_more'),
        ('attendance', '0012_auto_20250515_1807'),
    ]

    operations = [
    ]
