# Generated by Django 3.2.7 on 2025-06-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_merge_0011_holiday_and_more_0012_auto_20250515_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_attendance_data',
            name='shift_type',
            field=models.CharField(choices=[('general', 'General'), ('morning', 'Morning'), ('evening', 'Evening'), ('both', 'Both')], default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance_employee_data',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance_attendance_data',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
