# Generated by Django 3.2.7 on 2025-06-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20250602_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance_attendance_data')),
            ],
            options={
                'db_table': 'daily_report',
                'ordering': ['-attendance__date', '-submitted_at'],
            },
        ),
    ]
