# Generated by Django 3.2.7 on 2025-06-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_reportcomment_reportreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='attendance.attendance_attendance_data'),
        ),
    ]
