# Generated by Django 3.2.7 on 2025-06-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_reportcomment_reportreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_employee_data',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterModelTable(
            name='announcementread',
            table='announcement_read',
        ),
    ]
