# Generated by Django 4.2.22 on 2025-06-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_dailyreport_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_employee_data',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance_attendance_data'),
        ),
    ]
