# Generated by Django 3.2.7 on 2025-06-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_attendance_employee_data_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcementread',
            table='announcement_read',
        ),
        migrations.CreateModel(
            name='SectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_reports', to='attendance.dailyreport')),
            ],
            options={
                'db_table': 'section_report',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HourlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('task_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_reports', to='attendance.dailyreport')),
            ],
            options={
                'db_table': 'hourly_report',
                'ordering': ['hour'],
            },
        ),
    ]
